from domain.exceptions.domain_exception import DomainException


class ValidationException(DomainException):
    pass
