from domain.exceptions.domain_exception import DomainException


class ValueObjectException(DomainException):
    pass
